FROM node:18-alpine
WORKDIR /app
COPY package*.json ./
RUN npm install -g ts-node-dev nodemon && npm install
COPY . .
EXPOSE 3001
CMD ["npx", "ts-node-dev", "--respawn", "--transpile-only", "src/index.ts"]
